# Generated by Django 3.2 on 2023-03-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('salidaInventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidainventario',
            name='diario',
        ),
        migrations.RemoveField(
            model_name='salidainventario',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='salidainventario',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='cantidad_solicitada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='estado',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='justificacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salidainventario',
            name='producto_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoId', to='producto.producto'),
        ),
    ]
