# Generated by Django 3.2 on 2023-03-25 21:31

import apps.base.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True)),
                ('precio_unitario', models.CharField(max_length=255)),
                ('unidades_disponibles', models.CharField(blank=True, max_length=255, null=True)),
                ('vendible', models.BooleanField(default=False)),
                ('comprable', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategoria', to='producto.categoria')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subuom', to='producto.uom')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
