# Generated by Django 3.2 on 2023-03-29 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_unidades_disponibles'),
        ('proveedor', '0002_auto_20230325_1544'),
        ('facturaProveedor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='diario',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='facturaproveedor',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='producto',
            field=models.ManyToManyField(blank=True, to='producto.Producto'),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedorId', to='proveedor.proveedor'),
        ),
    ]
