# Generated by Django 3.2 on 2023-03-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('solicitudSuministro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsuministro',
            name='medida',
        ),
        migrations.RemoveField(
            model_name='solicitudsuministro',
            name='partida',
        ),
        migrations.AlterField(
            model_name='solicitudsuministro',
            name='producto_entregado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoEntregado', to='producto.producto'),
        ),
        migrations.AlterField(
            model_name='solicitudsuministro',
            name='producto_solicitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productoSolicitado', to='producto.producto'),
        ),
    ]
