# Generated by Django 3.2 on 2023-03-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudSuministro', '0002_auto_20230325_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudsuministro',
            name='cantidad_real',
        ),
        migrations.AlterField(
            model_name='solicitudsuministro',
            name='cantidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudsuministro',
            name='cantidad_solicitada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
