# Generated by Django 3.2 on 2023-03-19 17:46

import apps.base.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('cliente', models.CharField(max_length=255)),
                ('fecha_factura', models.DateField(auto_now_add=True, null=True)),
                ('fecha_vencimiento', models.DateField(auto_now_add=True, null=True)),
                ('total', models.CharField(max_length=255, null=True)),
                ('estado', models.CharField(choices=[('Paid', 'Paid'), ('Draft', 'Draft'), ('Cancel', 'Cancel'), ('Process', 'Process'), ('Invoiced', 'Invoiced')], default='Draft', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Factura Cliente',
                'verbose_name_plural': 'Facturas Cliente',
            },
        ),
    ]
