# Generated by Django 3.2 on 2023-03-23 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturaCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='fecha_factura',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
