# Generated by Django 3.2 on 2023-03-26 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturaCliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacliente',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clienteId', to='facturaCliente.cliente'),
        ),
    ]
