# Generated by Django 3.2 on 2023-02-23 15:56

import apps.base.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('nombre', models.CharField(max_length=255, null=True, unique=True)),
                ('precio_unitario', models.CharField(max_length=255)),
                ('unidades_disponibles', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Producto Vendible',
                'verbose_name_plural': 'Productos Vendibles',
            },
        ),
    ]
