# Generated by Django 3.2 on 2023-02-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productosVendibles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagos',
            new_name='ProductosVendibles',
        ),
    ]
