# Generated by Django 3.2 on 2023-03-19 17:46

import apps.base.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('r_object', models.JSONField(default=apps.base.models.get_r_object, null=True)),
                ('tipo', models.CharField(max_length=255, null=True)),
                ('diario', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255, null=True)),
                ('fecha_pago', models.DateField(auto_now_add=True, null=True)),
                ('cantidad', models.CharField(max_length=255, null=True)),
                ('concepto', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
