# Generated by Django 3.2 on 2023-03-19 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagos',
            new_name='Pago',
        ),
    ]
