# Generated by Django 3.2 on 2023-03-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_rename_pagos_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], max_length=255, null=True),
        ),
    ]
