# Generated by Django 3.2 on 2023-03-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_auto_20230325_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='diario',
        ),
    ]
